// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package ebs

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*Config) HCL2Schema() hcldec.ObjectSpec {
	s := map[string]hcldec.Spec{
		"AMIMappings": nil,
		"LaunchMappings": nil,
		"VolumeRunTags": nil,
	}
	return hcldec.ObjectSpec(s)
}

