// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package ecs

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*AlicloudAccessConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"AlicloudAccessKey":      &hcldec.AttrSpec{Name: "access_key", Type: cty.String, Required: false},
		"AlicloudSecretKey":      &hcldec.AttrSpec{Name: "secret_key", Type: cty.String, Required: false},
		"AlicloudRegion":         &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"AlicloudSkipValidation": &hcldec.AttrSpec{Name: "skip_region_validation", Type: cty.Bool, Required: false},
		"SecurityToken":          &hcldec.AttrSpec{Name: "security_token", Type: cty.String, Required: false},
	}
	return s
}
