// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package ecs

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*RunConfig) HCL2Spec() hcldec.ObjectSpec {
	s := map[string]hcldec.Spec{
		"AssociatePublicIpAddress": &hcldec.AttrSpec{Name: "associate_public_ip_address", Type: cty.Bool, Required: false},
		"ZoneId":                   &hcldec.AttrSpec{Name: "zone_id", Type: cty.String, Required: false},
		"IOOptimized":              &hcldec.AttrSpec{Name: "io_optimized", Type: cty.Bool, Required: false},
		"InstanceType":             &hcldec.AttrSpec{Name: "instance_type", Type: cty.String, Required: false},
		"Description":              &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"AlicloudSourceImage":      &hcldec.AttrSpec{Name: "source_image", Type: cty.String, Required: false},
		"ForceStopInstance":        &hcldec.AttrSpec{Name: "force_stop_instance", Type: cty.Bool, Required: false},
		"DisableStopInstance":      &hcldec.AttrSpec{Name: "disable_stop_instance", Type: cty.Bool, Required: false},
		"SecurityGroupId":          &hcldec.AttrSpec{Name: "security_group_id", Type: cty.String, Required: false},
		"SecurityGroupName":        &hcldec.AttrSpec{Name: "security_group_name", Type: cty.String, Required: false},
		"UserData":                 &hcldec.AttrSpec{Name: "user_data", Type: cty.String, Required: false},
		"UserDataFile":             &hcldec.AttrSpec{Name: "user_data_file", Type: cty.String, Required: false},
		"VpcId":                    &hcldec.AttrSpec{Name: "vpc_id", Type: cty.String, Required: false},
		"VpcName":                  &hcldec.AttrSpec{Name: "vpc_name", Type: cty.String, Required: false},
		"CidrBlock":                &hcldec.AttrSpec{Name: "vpc_cidr_block", Type: cty.String, Required: false},
		"VSwitchId":                &hcldec.AttrSpec{Name: "vswitch_id", Type: cty.String, Required: false},
		"VSwitchName":              &hcldec.AttrSpec{Name: "vswitch_name", Type: cty.String, Required: false},
		"InstanceName":             &hcldec.AttrSpec{Name: "instance_name", Type: cty.String, Required: false},
		"InternetChargeType":       &hcldec.AttrSpec{Name: "internet_charge_type", Type: cty.String, Required: false},
		"InternetMaxBandwidthOut":  &hcldec.AttrSpec{Name: "internet_max_bandwidth_out", Type: cty.Number, Required: false},
		"WaitSnapshotReadyTimeout": &hcldec.AttrSpec{Name: "wait_snapshot_ready_timeout", Type: cty.Number, Required: false},
		"Comm":                     nil,
		"SSHPrivateIp":             &hcldec.AttrSpec{Name: "ssh_private_ip", Type: cty.Bool, Required: false},
	}
	return hcldec.ObjectSpec(s)
}
