// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package communicator

import "github.com/hashicorp/packer/hcl2template"

func (*SSH) HCL2Schema() map[string]hcl2template.Schema {
	return map[string]hcl2template.Schema{
		"SSHHost": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHPort": {
			Type:        hcl2template.TypeInt,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHUsername": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHPassword": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHKeyPairName": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHTemporaryKeyPairName": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHClearAuthorizedKeys": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHPrivateKeyFile": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHPty": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHTimeout": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHAgentAuth": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHDisableAgentForwarding": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHHandshakeAttempts": {
			Type:        hcl2template.TypeInt,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHBastionHost": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHBastionPort": {
			Type:        hcl2template.TypeInt,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHBastionAgentAuth": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHBastionUsername": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHBastionPassword": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHBastionPrivateKeyFile": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHFileTransferMethod": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHProxyHost": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHProxyPort": {
			Type:        hcl2template.TypeInt,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHProxyUsername": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHProxyPassword": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHKeepAliveInterval": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHReadWriteTimeout": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHRemoteTunnels": {
			Type:        hcl2template.TypeList,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SSHLocalTunnels": {
			Type:        hcl2template.TypeList,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
	}
}

func (*WinRM) HCL2Schema() map[string]hcl2template.Schema {
	return map[string]hcl2template.Schema{
		"WinRMUser": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"WinRMPassword": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"WinRMHost": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"WinRMPort": {
			Type:        hcl2template.TypeInt,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"WinRMTimeout": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"WinRMUseSSL": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"WinRMInsecure": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"WinRMUseNTLM": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
	}
}

