// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*ISOConfig) HCL2Spec() hcldec.ObjectSpec {
	s := map[string]hcldec.Spec{
		"ISOChecksum":     &hcldec.AttrSpec{Name: "iso_checksum", Type: cty.String, Required: false},
		"ISOChecksumURL":  &hcldec.AttrSpec{Name: "iso_checksum_url", Type: cty.String, Required: false},
		"ISOChecksumType": &hcldec.AttrSpec{Name: "iso_checksum_type", Type: cty.String, Required: false},
		"RawSingleISOUrl": &hcldec.AttrSpec{Name: "iso_url", Type: cty.String, Required: false},
		"ISOUrls":         &hcldec.AttrSpec{Name: "iso_urls", Type: cty.List(cty.String), Required: false},
		"TargetPath":      &hcldec.AttrSpec{Name: "iso_target_path", Type: cty.String, Required: false},
		"TargetExtension": &hcldec.AttrSpec{Name: "iso_target_extension", Type: cty.String, Required: false},
	}
	return hcldec.ObjectSpec(s)
}
