// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package common

import "github.com/hashicorp/packer/hcl2template"

func (*ISOConfig) HCL2Schema() map[string]hcl2template.Schema {
	return map[string]hcl2template.Schema{
		"ISOChecksum": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"ISOChecksumURL": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"ISOChecksumType": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"RawSingleISOUrl": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"ISOUrls": {
			Type:        hcl2template.TypeList,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"TargetPath": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"TargetExtension": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
	}
}

