// Code generated by "hcl2-schema -type ISOConfig"; DO NOT EDIT.

package common

import "github.com/hashicorp/packer/hcl2template"

func (*ISOConfig) HCL2Schema() {
	return map[string]hcl2template.Schema{
		"ISOChecksum": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"ISOChecksumURL": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"ISOChecksumType": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"RawSingleISOUrl": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"TargetPath": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"TargetExtension": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
	}
}
