// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package common

import "github.com/hashicorp/packer/hcl2template"

func (*AccessConfig) HCL2Schema() map[string]hcl2template.Schema {
	s := map[string]hcl2template.Schema{
		"AccessKey": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"CustomEndpointEc2": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"DecodeAuthZMessages": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"InsecureSkipTLSVerify": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"MFACode": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"ProfileName": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"RawRegion": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SecretKey": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SkipValidation": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"SkipMetadataApiCheck": {
			Type:        hcl2template.TypeBool,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"Token": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"VaultAWSEngine": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
	}
	return s
}

func (*VaultAWSEngineOptions) HCL2Schema() map[string]hcl2template.Schema {
	s := map[string]hcl2template.Schema{
		"Name": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"RoleARN": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"TTL": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
		"EngineName": {
			Type:        hcl2template.TypeString,
			Required:    false,
			Optional:    true,
			Description: "Auto generated field",
		},
	}
	return s
}

