// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*AMIConfig) HCL2Spec() hcldec.ObjectSpec {
	s := map[string]hcldec.Spec{
		"AMIName":                 &hcldec.AttrSpec{Name: "AMIName", Type: cty.String, Required: false},
		"AMIDescription":          &hcldec.AttrSpec{Name: "AMIDescription", Type: cty.String, Required: false},
		"AMIVirtType":             &hcldec.AttrSpec{Name: "AMIVirtType", Type: cty.String, Required: false},
		"AMIUsers":                &hcldec.AttrSpec{Name: "AMIUsers", Type: cty.List(cty.String), Required: false},
		"AMIGroups":               &hcldec.AttrSpec{Name: "AMIGroups", Type: cty.List(cty.String), Required: false},
		"AMIProductCodes":         &hcldec.AttrSpec{Name: "AMIProductCodes", Type: cty.List(cty.String), Required: false},
		"AMIRegions":              &hcldec.AttrSpec{Name: "AMIRegions", Type: cty.List(cty.String), Required: false},
		"AMISkipRegionValidation": &hcldec.AttrSpec{Name: "AMISkipRegionValidation", Type: cty.Bool, Required: false},
		"AMITags":                 nil,
		"AMIENASupport":           &hcldec.AttrSpec{Name: "AMIENASupport", Type: cty.Bool, Required: false},
		"AMISriovNetSupport":      &hcldec.AttrSpec{Name: "AMISriovNetSupport", Type: cty.Bool, Required: false},
		"AMIForceDeregister":      &hcldec.AttrSpec{Name: "AMIForceDeregister", Type: cty.Bool, Required: false},
		"AMIForceDeleteSnapshot":  &hcldec.AttrSpec{Name: "AMIForceDeleteSnapshot", Type: cty.Bool, Required: false},
		"AMIEncryptBootVolume":    &hcldec.AttrSpec{Name: "AMIEncryptBootVolume", Type: cty.Bool, Required: false},
		"AMIKmsKeyId":             &hcldec.AttrSpec{Name: "AMIKmsKeyId", Type: cty.String, Required: false},
		"AMIRegionKMSKeyIDs":      nil,
		"AMISkipBuildRegion":      &hcldec.AttrSpec{Name: "AMISkipBuildRegion", Type: cty.Bool, Required: false},
		"SnapshotTags":            nil,
		"SnapshotUsers":           &hcldec.AttrSpec{Name: "SnapshotUsers", Type: cty.List(cty.String), Required: false},
		"SnapshotGroups":          &hcldec.AttrSpec{Name: "SnapshotGroups", Type: cty.List(cty.String), Required: false},
	}
	return hcldec.ObjectSpec(s)
}
