// Code generated by "hcl2-schema"; DO NOT EDIT.\n

package common

import (
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

func (*BlockDevice) HCL2Schema() hcldec.ObjectSpec {
	s := map[string]hcldec.Spec{
		"DeleteOnTermination": &hcldec.AttrSpec{Name:"DeleteOnTermination", Type:cty.Bool, Required:false},
		"DeviceName": &hcldec.AttrSpec{Name:"DeviceName", Type:cty.String, Required:false},
		"Encrypted": &hcldec.AttrSpec{Name:"Encrypted", Type:cty.Bool, Required:false},
		"IOPS": nil,
		"NoDevice": &hcldec.AttrSpec{Name:"NoDevice", Type:cty.Bool, Required:false},
		"SnapshotId": &hcldec.AttrSpec{Name:"SnapshotId", Type:cty.String, Required:false},
		"VirtualName": &hcldec.AttrSpec{Name:"VirtualName", Type:cty.String, Required:false},
		"VolumeType": &hcldec.AttrSpec{Name:"VolumeType", Type:cty.String, Required:false},
		"VolumeSize": nil,
		"KmsKeyId": &hcldec.AttrSpec{Name:"KmsKeyId", Type:cty.String, Required:false},
	}
	return hcldec.ObjectSpec(s)
}

